with open("24_21717.txt") as f:
    original = f.readline().strip()

data = original.split("RSQ")

a = []
for i in range(len(data) - 130):
    s = "RSQ" + "RSQ".join(data[i:i+129]) + "RSQ"
    a.append(s)

print(min(a, key=len))
s = "RSQRSQRSQRSQRSQQRRSQRSQRSQRSQRSQRSQRSQFRSQQQRSQRSQRSQRSQWRSQRSQRSQRSQGRSQSWRSQRRSQRSQSRSQGRSQRSQWWWRSQRRSQRSQRSQRSQWQSWWSRRSQRSQRSQRSQGRSQRSQQQWGWRSQRSQQRSQRRSQRSQWSSSRSQFRSQRSQRSQRSQRRSQGGRSQRSQFRRSQSRSQGFRSQRSQRSQFRSQRRSQSRSQQRSQRSQRSQRSQGQRRSQRSQQRSQSQRSQRSQSRSQWRSQGRSQWRRSQRSQQRSQRSRSQRSQRSQRSQRSQRSQRSQFRSQRRSQRSQRSQSGRSQQRSQRSQGRSQRSQRSQRSQRSQRSQFRQQGRRSQRSFRSQFRSQRWRSQRSQRWFRSQFRSQRSQRSQRSQRSQRSRSQRSQRSQRSQRSQGRRSQRSQRSQQRSRSQRSQRSQSRSQRSQRSQRSQFRSQRSQFGRSQRSQGWWRSQQWRSQRQGQQSRSQRSQRSQ"
print(original.index(s))
st = 2131750
en = st + len(s)
print(original[st:en + 2])
print(len(s) + 1)



